/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ViewVenda;

import Cliente.Cliente;
import DAO.ItensDaVendaDAO;
import DAO.VendaDAO;
import Funcionario.Funcionario;
import Itens_da_Venda.ItensDaVenda;
import Produto.Produto;
import Produto.VendaTableModel;
import Venda.Venda;
import java.awt.event.KeyEvent;
import java.awt.event.WindowEvent;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author Kaio Dias
 */
public class TelaVenda extends javax.swing.JInternalFrame {
    
    VendaTableModel model = new VendaTableModel();
    
    private boolean janelaAberta = true; //Instancia o model criado especificamente para vendas
    
    private Calendar dataAtual = Calendar.getInstance(); //Pega a data atual do sistema
    private Calendar dataVencimento = Calendar.getInstance(); //Pega a data atual do sistema para futuramente ser a data de vencimento
    private SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
    private SimpleDateFormat da = new SimpleDateFormat("yyyy/MM/dd");
    
    public TelaVenda(int permissaoUsuario) {
        initComponents();
        
        ((BasicInternalFrameUI)this.getUI()).setNorthPane(null); //Não permite a movimentação do JInternalFrame
        
        tabelaVenda.setModel(model);//Seta o model de compra
        model.isCellEditable(tabelaVenda.getSelectedRow(), tabelaVenda.getSelectedColumn()); //Torna a linha clicada editavel

        Thread loopThread = new Thread(() -> {//Loop que executa enquanto a janela estiver aberta
            while (janelaAberta) {
                double total = model.calcularTotalSubtotal();//Atualiza o campo do valor total da venda

                DecimalFormat df = new DecimalFormat("#0.00");//Formata os valores para 2 casas decimais
                String totalFormatado = df.format(total);
               
                txtTotal.setText(totalFormatado);
                
                if(model.getRowCount()!=0){//Se há produtos calcula o desconto 
                    double desconto = model.calcularEAtualizarSubtotal(model.getRowCount()-1);
                    String descontoFormatado = df.format(desconto);
                    txtDesconto.setText(descontoFormatado);
                }
                
                try {
                    Thread.sleep(100);
                } catch (InterruptedException e) {
                    e.printStackTrace();
                }
            }
        });
        
        loopThread.start(); //Inicia o loop

        txtData.setText(sdf.format(dataAtual.getTime()));//Pega a data atual

        dataVencimento.add(Calendar.DAY_OF_MONTH, 30); //Seta a data de vencimento
        txtVencimento.setText(sdf.format(dataVencimento.getTime()));
        
        VendaDAO v = new VendaDAO();
        txtIdVenda.setText(String.valueOf(v.numVendas()+1)); //Pega a quantidade de vendas pelo DAO e add 1
    }
    
    //Adiciona um produto a lista de venda e atualiza o subtotal do produto
    public void inserirProduto(Produto produto, ItensDaVenda item) {
        model.addRow(produto, item);

        model.calcularEAtualizarSubtotal(model.getRowCount() - 1);
    }
    
    //Adiciona o fucionário responsável pela venda
    public void inserirFuncionario(Funcionario f){
        txtFuncionario.setText(f.getNome());
        txtIdFuncionário.setText(String.valueOf(f.getIdFuncionario()));
    }
    
    //Adiciona o cliente da compra
    public void inserirCliente(Cliente c){
        txtCliente.setText(c.getNome());
        txtIdCliente.setText(String.valueOf(c.getIdCliente()));
    }

    //Confere se a janela está aberta para executar o loop
    public void windowClosing(WindowEvent e) {
        janelaAberta = false;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtDesconto = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtIdCliente = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnNovaVenda = new javax.swing.JButton();
        txtCliente = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtIdFuncionário = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtVencimento = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaVenda = new javax.swing.JTable();
        txtFuncionario = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnNovoItem = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtIdVenda = new javax.swing.JTextField();
        txtTotal = new javax.swing.JTextField();
        txtData = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(null);
        setForeground(java.awt.Color.white);
        setFrameIcon(null);
        setMinimumSize(new java.awt.Dimension(1080, 720));
        setPreferredSize(new java.awt.Dimension(1080, 720));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        txtDesconto.setEditable(false);
        txtDesconto.setEnabled(false);

        jLabel1.setText("ID Venda");

        jLabel9.setText("Total de descontos");

        txtIdCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtIdClienteKeyPressed(evt);
            }
        });

        jLabel2.setText("Cliente");

        btnNovaVenda.setText("Nova Venda");
        btnNovaVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovaVendaActionPerformed(evt);
            }
        });

        txtCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClienteActionPerformed(evt);
            }
        });
        txtCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtClienteKeyPressed(evt);
            }
        });

        jLabel3.setText("Funcionário");

        jLabel10.setBackground(new java.awt.Color(153, 153, 153));
        jLabel10.setForeground(new java.awt.Color(204, 204, 204));
        jLabel10.setText("* Tecle \"espaço\" para selecionar um cliente ou funcionário");

        txtIdFuncionário.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdFuncionárioActionPerformed(evt);
            }
        });
        txtIdFuncionário.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtIdFuncionárioKeyPressed(evt);
            }
        });

        jLabel4.setText("Data:");

        txtVencimento.setEnabled(false);

        jLabel5.setText("Vencimento:");

        tabelaVenda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Item", "Id", "Código", "Nome", "Preço", "Quantidade", "Desconto %", "Subtotal"
            }
        ));
        tabelaVenda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tabelaVendaKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaVenda);

        jTabbedPane1.addTab("Itens da Venda", jScrollPane1);

        txtFuncionario.setActionCommand("null");
        txtFuncionario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtFuncionarioKeyPressed(evt);
            }
        });

        jLabel6.setText("ID");

        jLabel7.setText("ID");

        btnNovoItem.setText("Novo Item");
        btnNovoItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoItemActionPerformed(evt);
            }
        });

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir Item");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        jLabel8.setText("Total da Venda");

        txtIdVenda.setEditable(false);
        txtIdVenda.setEnabled(false);

        txtTotal.setEditable(false);
        txtTotal.setEnabled(false);

        txtData.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtIdVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addGap(30, 30, 30)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtIdFuncionário, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtIdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtFuncionario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtVencimento, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnNovoItem)
                        .addGap(18, 18, 18)
                        .addComponent(btnExcluir)
                        .addGap(18, 18, 18)
                        .addComponent(btnSalvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnNovaVenda)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jTabbedPane1))
                .addGap(39, 39, 39))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4)
                    .addComponent(txtIdVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtVencimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtIdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel2)))
                            .addGap(29, 29, 29)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3)
                                .addComponent(txtIdFuncionário, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6)))
                        .addComponent(jLabel5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNovoItem)
                    .addComponent(btnExcluir)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalvar)
                    .addComponent(txtDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNovaVenda))
                .addContainerGap(78, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdClienteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdClienteKeyPressed
        // TODO add your handling code here:

        if (evt.getKeyCode() == KeyEvent.VK_SPACE) {
            TelaClientesvenda telaClientes = new TelaClientesvenda();

            telaClientes.setTelaVenda(this);
            telaClientes.setVisible(true);
        }
    }//GEN-LAST:event_txtIdClienteKeyPressed

    private void btnNovaVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovaVendaActionPerformed
        // TODO add your handling code here:
        VendaDAO vendaDao = new VendaDAO();

        txtIdVenda.setText(String.valueOf(vendaDao.numVendas()+1));

        btnSalvar.setEnabled(true);

        txtCliente.setText("");
        txtFuncionario.setText("");
        txtIdCliente.setText("");
        txtIdFuncionário.setText("");

        btnExcluir.setEnabled(true);
        btnNovoItem.setEnabled(true);
        btnSalvar.setEnabled(true);

        model.removeAllRows();
    }//GEN-LAST:event_btnNovaVendaActionPerformed

    private void txtClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClienteActionPerformed

    private void txtClienteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtClienteKeyPressed
        // TODO add your handling code here:

        if (evt.getKeyCode() == KeyEvent.VK_SPACE) {
            TelaClientesvenda telaClientes = new TelaClientesvenda();

            telaClientes.setTelaVenda(this);
            telaClientes.setVisible(true);
        }
    }//GEN-LAST:event_txtClienteKeyPressed

    private void txtIdFuncionárioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdFuncionárioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdFuncionárioActionPerformed

    private void txtIdFuncionárioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdFuncionárioKeyPressed
        // TODO add your handling code here:

        if (evt.getKeyCode() == KeyEvent.VK_SPACE) {
            TelaFuncionariosVenda telaFuncionario = new TelaFuncionariosVenda();

            telaFuncionario.atualizarTabela();
            telaFuncionario.setTelaVenda(this);
            telaFuncionario.setVisible(true);
        }
    }//GEN-LAST:event_txtIdFuncionárioKeyPressed

    private void tabelaVendaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tabelaVendaKeyPressed
        TelaProdutosVenda telaProdutos = new TelaProdutosVenda(this); 
        telaProdutos.setVisible(true);
    }//GEN-LAST:event_tabelaVendaKeyPressed

    private void txtFuncionarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFuncionarioKeyPressed

        if (evt.getKeyCode() == KeyEvent.VK_SPACE) {
            TelaFuncionariosVenda telaFuncionario = new TelaFuncionariosVenda();

            telaFuncionario.atualizarTabela();
            telaFuncionario.setTelaVenda(this);
            telaFuncionario.setVisible(true);
        }

    }//GEN-LAST:event_txtFuncionarioKeyPressed

    private void btnNovoItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoItemActionPerformed
        // TODO add your handling code here:

        TelaProdutosVenda telaProdutos = new TelaProdutosVenda(this); // Passe a instância de TelaVenda
        telaProdutos.setVisible(true);
    }//GEN-LAST:event_btnNovoItemActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        // TODO add your handling code here:
        VendaDAO vendaDao = new VendaDAO();
        Venda v = new Venda();
        Cliente cli = new Cliente();
        Funcionario func = new Funcionario();
        ItensDaVenda iv = new ItensDaVenda();
        ItensDaVendaDAO itemDao = new ItensDaVendaDAO();
        Produto p = new Produto();

        //Realisa a venda se todos os campos forem preenchidos
        if((txtCliente.getText().isEmpty() || txtIdCliente.getText().isEmpty()) || (txtFuncionario.getText().isEmpty()
            || txtIdFuncionário.getText().isEmpty()) || tabelaVenda.getRowCount() <=0){
        JOptionPane.showMessageDialog(this, "Preencha todos os campos!", "Atenção!", JOptionPane.ERROR_MESSAGE);
        }
        else{
            //Preenche o objeto de venda 
            v.setIdVenda(Integer.parseInt(txtIdVenda.getText()));
            v.setDataVenda(da.format(dataAtual.getTime()));
            v.setTotal(Double.parseDouble(txtTotal.getText()));

            cli.setIdCliente(Integer.parseInt(txtIdCliente.getText()));
            v.setCliente(cli);

            func.setIdFuncionario(Integer.parseInt(txtIdFuncionário.getText()));
            v.setFuncionario(func);

            v.setStatusVenda("Concluida");
            v.setDesconto(Double.parseDouble(txtDesconto.getText()));

            vendaDao.create(v);

            for (int i = 0; i < model.getRowCount(); i++) {
                iv.setVenda(v);
                iv.setData(da.format(dataAtual.getTime()));

                p.setIdProduto(Integer.parseInt(model.getValueAt(i, 1).toString()));
                iv.setProduto(p);

                iv.setQuantidade(Double.parseDouble(model.getValueAt(i, 5).toString()));

                p.setPrecoUn(Double.parseDouble(model.getValueAt(i, 4).toString()));
                iv.setProduto(p);

                iv.setDesconto(Double.parseDouble(model.getValueAt(i, 6).toString()));
                iv.setSubtotal(Double.parseDouble(model.getValueAt(i, 7).toString()));

                //Insere a venda no BD pelo DAO
                itemDao.create(iv);
                itemDao.atualizarEstoque(iv);
            }

            btnExcluir.setEnabled(false);
            btnNovoItem.setEnabled(false);
            btnSalvar.setEnabled(false);
        }

    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        // TODO add your handling code here:

        if (tabelaVenda.getSelectedRow() != -1) {
            model.removeRow(tabelaVenda.getSelectedRow());
        }
    }//GEN-LAST:event_btnExcluirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnNovaVenda;
    private javax.swing.JButton btnNovoItem;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tabelaVenda;
    private javax.swing.JTextField txtCliente;
    private javax.swing.JTextField txtData;
    private javax.swing.JTextField txtDesconto;
    private javax.swing.JTextField txtFuncionario;
    private javax.swing.JTextField txtIdCliente;
    private javax.swing.JTextField txtIdFuncionário;
    private javax.swing.JTextField txtIdVenda;
    private javax.swing.JTextField txtTotal;
    private javax.swing.JTextField txtVencimento;
    // End of variables declaration//GEN-END:variables
}
