/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Backup;

import java.io.File;
import javax.swing.JFileChooser;

/**
 *
 * @author Kaio Dias
 */
public class TelaRestaurarBackup extends javax.swing.JFrame {

    /**
     * Creates new form TelaBackUp
     */
    public TelaRestaurarBackup() {
        initComponents();
    }

    String pasta = null;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtLocalDoArquivo = new javax.swing.JTextField();
        btnEscolher = new javax.swing.JButton();
        btnRestaurar = new javax.swing.JButton();
        txtMensagem = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Fazer Backup de dados");

        btnEscolher.setText("Escolher arquivo");
        btnEscolher.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnEscolherMouseReleased(evt);
            }
        });

        btnRestaurar.setText("Restaurar dados");
        btnRestaurar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnRestaurarMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnRestaurar)
                        .addGap(40, 40, 40)
                        .addComponent(txtMensagem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(txtLocalDoArquivo, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(btnEscolher)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLocalDoArquivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEscolher))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRestaurar)
                    .addComponent(txtMensagem, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnEscolherMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEscolherMouseReleased
        // TODO add your handling code here:
        JFileChooser fc = new JFileChooser();
        fc.showOpenDialog(this);
        try {
            File f = fc.getSelectedFile();
            pasta = f.getAbsolutePath();
            pasta = pasta.replace('\\', '/');

            txtLocalDoArquivo.setText(pasta);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnEscolherMouseReleased

    private void btnRestaurarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRestaurarMouseReleased
        // TODO add your handling code here:
        if (txtLocalDoArquivo.getText().equals("")) {
            txtMensagem.setText("*ESCOLHA O ARQUIVO PARA RETAURAR*");
        } else {
            String dbUsuario = "root";
            String dbSenha = "";

            String[] restoreCmd = new String[]{"C:/xampp/mysql/bin/mysql.exe ", "--user=" + dbUsuario, "--password=" + dbSenha, "-e", "source " + pasta};
            Process runtimProcess;
            try {
                runtimProcess = Runtime.getRuntime().exec(restoreCmd);
                int proceCom = runtimProcess.waitFor();

                if (proceCom == 0) {
                    txtMensagem.setText("Restaurado com sucesso");
                } else {
                    txtMensagem.setText("Não foi possível restaurar os dados");
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_btnRestaurarMouseReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEscolher;
    private javax.swing.JButton btnRestaurar;
    private javax.swing.JTextField txtLocalDoArquivo;
    private javax.swing.JLabel txtMensagem;
    // End of variables declaration//GEN-END:variables
}
