/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ViewCompra;

import Compra.Compra;
import DAO.CompraDAO;
import DAO.ItensDaCompraDAO;
import Fornecedor.Fornecedor;
import Funcionario.Funcionario;
import Itens_da_Compra.ItensDaCompra;
import Produto.CompraTableModel;
import Produto.Produto;
import java.awt.event.KeyEvent;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JOptionPane;

/**
 *
 * @author Kaio Dias
 */
public class TelaCompra extends javax.swing.JInternalFrame {
    
    CompraTableModel model = new CompraTableModel();
    /**
     * Creates new form TelaVenda
     */

    private boolean janelaAberta = true;
    
    private Calendar dataAtual = Calendar.getInstance();
    private Calendar dataVencimento = Calendar.getInstance();
    private SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
    private SimpleDateFormat da = new SimpleDateFormat("yyyy/MM/dd");
    
    public TelaCompra() {
        initComponents();
        tabelaCompra.setModel(model);
        model.isCellEditable(tabelaCompra.getSelectedRow(), tabelaCompra.getSelectedColumn());

//        this.addWindowListener(new java.awt.event.WindowAdapter() {
//            @Override
//            public void windowClosing(java.awt.event.WindowEvent windowEvent) {
//                formWindowClosing(windowEvent);
//            }
//        });

        Thread loopThread = new Thread(() -> {
            while (janelaAberta) {
                double total = model.calcularTotalSubtotal();

                DecimalFormat df = new DecimalFormat("#0.00");
                String totalFormatado = df.format(total);
               
                txtTotal.setText(totalFormatado);
                
                if(model.getRowCount()!=0){
                    double desconto = model.calcularEAtualizarSubtotal(model.getRowCount()-1);
                    String descontoFormatado = df.format(desconto);
                    txtDesconto.setText(descontoFormatado);
                }
                
                try {
                    Thread.sleep(100);
                } catch (InterruptedException e) {
                    e.printStackTrace();
                }
            }
        });
        
        loopThread.start();

        txtData.setText(sdf.format(dataAtual.getTime()));

        dataVencimento.add(Calendar.DAY_OF_MONTH, 30);
        txtVencimento.setText(sdf.format(dataVencimento.getTime()));
        
        CompraDAO c = new CompraDAO();
        txtIdCompra.setText(String.valueOf(c.numCompra()+1));
    }

    
    public void inserirProduto(Produto produto, ItensDaCompra item) {
        model.addRow(produto, item);
        model.calcularEAtualizarSubtotal(model.getRowCount() - 1);
    }
    
    public void inserirFuncionario(Funcionario f){
        txtFuncionario.setText(f.getNome());
        txtIdFuncionário.setText(String.valueOf(f.getIdFuncionario()));
    }
    
    public void inserirFornecedor(Fornecedor f){
        txtFornecedor.setText(f.getNome());
        txtIdFornecedor.setText(String.valueOf(f.getIdFornecedor()));
    }

    private void fecharJanela() {
        janelaAberta = false; // Define a variável para false
        dispose(); // Fecha a janela
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        btnNovoItem = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtIdCompra = new javax.swing.JTextField();
        txtTotal = new javax.swing.JTextField();
        txtDesconto = new javax.swing.JTextField();
        txtData = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtIdFornecedor = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnNovaCompra = new javax.swing.JButton();
        txtFornecedor = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtIdFuncionário = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtVencimento = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaCompra = new javax.swing.JTable();
        txtFuncionario = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(null);
        setForeground(java.awt.Color.white);
        setFrameIcon(null);
        setMinimumSize(new java.awt.Dimension(1080, 720));
        setPreferredSize(new java.awt.Dimension(1080, 720));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setText("ID");

        btnNovoItem.setText("Novo Item");
        btnNovoItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoItemActionPerformed(evt);
            }
        });

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir Item");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        jLabel8.setText("Total da Compra");

        txtIdCompra.setEditable(false);
        txtIdCompra.setEnabled(false);

        txtTotal.setEditable(false);
        txtTotal.setEnabled(false);

        txtDesconto.setEditable(false);
        txtDesconto.setEnabled(false);

        txtData.setEnabled(false);
        txtData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDataActionPerformed(evt);
            }
        });

        jLabel1.setText("ID Compra");

        jLabel9.setText("Total de descontos");

        txtIdFornecedor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtIdFornecedorKeyPressed(evt);
            }
        });

        jLabel2.setText("Fornecedor");

        btnNovaCompra.setText("Nova Compra");
        btnNovaCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovaCompraActionPerformed(evt);
            }
        });

        txtFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFornecedorActionPerformed(evt);
            }
        });
        txtFornecedor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtFornecedorKeyPressed(evt);
            }
        });

        jLabel3.setText("Funcionário");

        txtIdFuncionário.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdFuncionárioActionPerformed(evt);
            }
        });
        txtIdFuncionário.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtIdFuncionárioKeyPressed(evt);
            }
        });

        jLabel4.setText("Data:");

        txtVencimento.setEnabled(false);

        jLabel5.setText("Vencimento:");

        tabelaCompra.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Item", "Id", "Código", "Nome", "Preço", "Quantidade", "Desconto %", "Subtotal"
            }
        ));
        tabelaCompra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tabelaCompraKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaCompra);

        jTabbedPane1.addTab("Itens da Compra", jScrollPane1);

        txtFuncionario.setActionCommand("null");
        txtFuncionario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtFuncionarioKeyPressed(evt);
            }
        });

        jLabel6.setText("ID");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtIdCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(30, 30, 30)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtIdFuncionário, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtIdFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtFuncionario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtData)
                            .addComponent(txtVencimento, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnNovoItem)
                        .addGap(18, 18, 18)
                        .addComponent(btnExcluir)
                        .addGap(18, 18, 18)
                        .addComponent(btnSalvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnNovaCompra)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(33, 33, 33))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4)
                    .addComponent(txtIdCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtVencimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtIdFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel2)))
                            .addGap(29, 29, 29)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3)
                                .addComponent(txtIdFuncionário, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(txtFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNovoItem)
                    .addComponent(btnExcluir)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalvar)
                    .addComponent(txtDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNovaCompra))
                .addContainerGap(102, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNovoItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoItemActionPerformed
        // TODO add your handling code here:

        TelaProdutosCompra telaProdutos = new TelaProdutosCompra(this); // Passe a instância de TelaVenda
        telaProdutos.setVisible(true);
    }//GEN-LAST:event_btnNovoItemActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        // TODO add your handling code here:
        CompraDAO compraDao = new CompraDAO();
        Compra c = new Compra();

        Funcionario func = new Funcionario();

        Fornecedor forn = new Fornecedor();

        ItensDaCompra ic = new ItensDaCompra();
        ItensDaCompraDAO itemDao = new ItensDaCompraDAO();

        Produto p = new Produto();

        if((txtFornecedor.getText().isEmpty() || txtIdFornecedor.getText().isEmpty()) || (txtFuncionario.getText().isEmpty()
            || txtIdFuncionário.getText().isEmpty()) || tabelaCompra.getRowCount() <=0){
        JOptionPane.showMessageDialog(this, "Preencha todos os campos!", "Atenção!", JOptionPane.ERROR_MESSAGE);
        }
        else{
            c.setIdCompra(Integer.parseInt(txtIdCompra.getText()));
            c.setDataCompra(da.format(dataAtual.getTime()).toString());
            c.setTotal(Double.parseDouble(txtTotal.getText()));

            forn.setIdFornecedor(Integer.parseInt(txtIdFornecedor.getText()));
            c.setFornecedor(forn);

            func.setIdFuncionario(Integer.parseInt(txtIdFuncionário.getText()));
            c.setFuncionario(func);

            c.setDesconto(Double.parseDouble(txtDesconto.getText()));

            compraDao.create(c);

            //idVenda, data, idProduto, quantidade, precoUn, desconto, total
            for (int i = 0; i < model.getRowCount(); i++) {
                ic.setCompra(c);
                //ic.setData(da.format(dataAtual.getTime()).toString());

                p.setIdProduto(Integer.parseInt(model.getValueAt(i, 1).toString()));
                ic.setProduto(p);

                ic.setQuantidade(Double.parseDouble(model.getValueAt(i, 5).toString()));

                p.setPrecoCusto(Double.parseDouble(model.getValueAt(i, 4).toString()));
                ic.setProduto(p);

                ic.setDesconto(Double.parseDouble(model.getValueAt(i, 6).toString()));
                ic.setSubtotal(Double.parseDouble(model.getValueAt(i, 7).toString()));

                itemDao.create(ic);
                itemDao.atualizarEstoque(ic);
            }

            btnExcluir.setEnabled(false);
            btnNovoItem.setEnabled(false);
            btnSalvar.setEnabled(false);
        }

    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        // TODO add your handling code here:

        if (tabelaCompra.getSelectedRow() != -1) {
            model.removeRow(tabelaCompra.getSelectedRow());
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void txtDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDataActionPerformed

    private void txtIdFornecedorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdFornecedorKeyPressed
        // TODO add your handling code here:

        if (evt.getKeyCode() == KeyEvent.VK_SPACE) {
            TelaFornecedoresCompra telaFornecedor = new TelaFornecedoresCompra();

            telaFornecedor.setTelaCompra(this);
            telaFornecedor.setVisible(true);
        }
    }//GEN-LAST:event_txtIdFornecedorKeyPressed

    private void btnNovaCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovaCompraActionPerformed
        // TODO add your handling code here:
        CompraDAO compraDao = new CompraDAO();

        txtIdCompra.setText(String.valueOf(compraDao.numCompra()+1));

        btnSalvar.setEnabled(true);

        txtFornecedor.setText("");
        txtFuncionario.setText("");
        txtIdFornecedor.setText("");
        txtIdFuncionário.setText("");

        btnExcluir.setEnabled(true);
        btnNovoItem.setEnabled(true);
        btnSalvar.setEnabled(true);

        model.removeAllRows();
    }//GEN-LAST:event_btnNovaCompraActionPerformed

    private void txtFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFornecedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFornecedorActionPerformed

    private void txtFornecedorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFornecedorKeyPressed
        // TODO add your handling code here:

        if (evt.getKeyCode() == KeyEvent.VK_SPACE) {
            TelaFornecedoresCompra telaFornecedor = new TelaFornecedoresCompra();

            telaFornecedor.setTelaCompra(this);
            telaFornecedor.setVisible(true);
        }
    }//GEN-LAST:event_txtFornecedorKeyPressed

    private void txtIdFuncionárioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdFuncionárioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdFuncionárioActionPerformed

    private void txtIdFuncionárioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdFuncionárioKeyPressed
        // TODO add your handling code here:

        if (evt.getKeyCode() == KeyEvent.VK_SPACE) {
            TelaFuncionariosCompra telaFuncionario = new TelaFuncionariosCompra();

            telaFuncionario.atualizarTabela();
            telaFuncionario.setTelaCompra(this);
            telaFuncionario.setVisible(true);
        }
    }//GEN-LAST:event_txtIdFuncionárioKeyPressed

    private void tabelaCompraKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tabelaCompraKeyPressed
        TelaProdutosCompra telaProdutos = new TelaProdutosCompra(this); // Passe a instância de TelaVenda
        telaProdutos.setVisible(true);
    }//GEN-LAST:event_tabelaCompraKeyPressed

    private void txtFuncionarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFuncionarioKeyPressed

        if (evt.getKeyCode() == KeyEvent.VK_SPACE) {
            TelaFuncionariosCompra telaFuncionario = new TelaFuncionariosCompra();

            telaFuncionario.atualizarTabela();
            telaFuncionario.setTelaCompra(this);
            telaFuncionario.setVisible(true);
        }

    }//GEN-LAST:event_txtFuncionarioKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnNovaCompra;
    private javax.swing.JButton btnNovoItem;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tabelaCompra;
    private javax.swing.JTextField txtData;
    private javax.swing.JTextField txtDesconto;
    private javax.swing.JTextField txtFornecedor;
    private javax.swing.JTextField txtFuncionario;
    private javax.swing.JTextField txtIdCompra;
    private javax.swing.JTextField txtIdFornecedor;
    private javax.swing.JTextField txtIdFuncionário;
    private javax.swing.JTextField txtTotal;
    private javax.swing.JTextField txtVencimento;
    // End of variables declaration//GEN-END:variables
}
