/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ViewCompra;

import DAO.FornecedorDAO;
import Fornecedor.Fornecedor;
import java.awt.event.KeyEvent;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Kaio Dias
 */
public class TelaFornecedoresCompra extends javax.swing.JFrame {

    /**
     * Creates new form TelaListaFornecedores
     */
    
    private TelaCompra telaCompra;

    //Recebe uma instância da tela de compra 
    public void setTelaCompra(TelaCompra telaCompra) {
        this.telaCompra = telaCompra;
    }
    
    
    public TelaFornecedoresCompra() {
        initComponents();
        //Preenche a tabela de fornecedores cadastrados assim que a tela é exibida
        atualizarTabela();
    }

    //Preenche a tabela de fornecedores cadastrados
    private void atualizarTabela() {
        DefaultTableModel modelo = (DefaultTableModel) tabelaForn.getModel();
        modelo.setRowCount(0); // Limpa os dados da tabela

        FornecedorDAO fornecedorDAO = new FornecedorDAO();
        List<Fornecedor> fornecedores = fornecedorDAO.read(); // Obtem a lista de fornecedores

        //Preenche a tabela com os dados vindos da lista de fornecedores
        for (Fornecedor f : fornecedores) {
            modelo.addRow(new Object[]{
                f.getIdFornecedor(),
                f.getNome(),
                f.getTelefone(),
                f.getEmail(),
                f.getCnpj()
            });
        }
    }

    //Busca fornecedores por nome ou cnpj
    public void searchJTableForName(String nome, String cnpj) {
        DefaultTableModel modelo = (DefaultTableModel) tabelaForn.getModel();
        modelo.setNumRows(0);
        FornecedorDAO fdao = new FornecedorDAO();

        for (Fornecedor f : fdao.searchForName(nome, cnpj)) {

            //Preenche a tabela de acordo com a busca
            modelo.addRow(new Object[]{
                f.getIdFornecedor(),
                f.getNome(),
                f.getTelefone(),
                f.getEmail(),
                f.getCnpj()
            });

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        tabelaForn = new javax.swing.JTable();
        txtBusca = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Lista de fornecedores");

        tabelaForn.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nome", "Telefone", "E-mail", "CNPJ"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaForn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaFornMouseClicked(evt);
            }
        });
        tabelaForn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tabelaFornKeyReleased(evt);
            }
        });
        jScrollPane3.setViewportView(tabelaForn);

        txtBusca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscaActionPerformed(evt);
            }
        });
        txtBusca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBuscaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscaKeyReleased(evt);
            }
        });

        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(589, 589, 589)
                        .addComponent(txtBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1)
                        .addGap(0, 136, Short.MAX_VALUE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(txtBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tabelaFornMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaFornMouseClicked
        // TODO add your handling code here:
        
        //Pega os dados do fornecedor selecionado e envia para a tela de compra 
       if (evt.getClickCount() == 2) { // Duplo clique
            if (tabelaForn.getSelectedRow() != -1) {
                
                Fornecedor f = new Fornecedor();
                
                f.setIdFornecedor(Integer.parseInt(tabelaForn.getValueAt(tabelaForn.getSelectedRow(), 0).toString()));
                f.setNome(tabelaForn.getValueAt(tabelaForn.getSelectedRow(), 1).toString());
                
                telaCompra.inserirFornecedor(f);
                this.dispose();
            }
        }
    }//GEN-LAST:event_tabelaFornMouseClicked

    private void tabelaFornKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tabelaFornKeyReleased
    }//GEN-LAST:event_tabelaFornKeyReleased

    private void txtBuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscaActionPerformed

    private void txtBuscaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscaKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            searchJTableForName(txtBusca.getText(), txtBusca.getText());
        }
        
    }//GEN-LAST:event_txtBuscaKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        searchJTableForName(txtBusca.getText(), txtBusca.getText());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtBuscaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscaKeyReleased
        // TODO add your handling code here:
        searchJTableForName(txtBusca.getText(), txtBusca.getText());
    }//GEN-LAST:event_txtBuscaKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tabelaForn;
    private javax.swing.JTextField txtBusca;
    // End of variables declaration//GEN-END:variables
}
