/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ViewPrincipal;

import ViewLogin.TelaLogin;
import ViewCadastro.TelaCadCategoria;
import ViewCadastro.TelaCadCliente;
import ViewCadastro.TelaCadFornecedor;
import ViewCadastro.TelaCadFuncionario;
import ViewCadastro.TelaCadProduto;
import ViewCompra.TelaCompra;
import ViewEstoque.TelaDeEstoque;
import ViewVenda.TelaVenda;
import java.awt.Color;
import java.awt.Dimension;
import java.time.LocalTime;
import javax.swing.JInternalFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Kaio Dias
 */
public class TelaPrincipal extends javax.swing.JFrame {

    private int confirmacaoTrocaUsuario;
    private int confirmarEncerrarSecao;
    private int permissaoUsuario;
    private String nomeUsuario;
    private TelaLogin telaLogin;
    private JInternalFrame home;
    private TelaVenda telaVenda;

    /**
     * Creates new form TelaPrincipal
     */
    //Inicia a tela principal e habilita os recursos do programa conforme a permissão do usuário
    //Recebe a tela Hoem
    //Recebe o nome de usuário da tela de login
    public TelaPrincipal(int permissaoUsuario, String nomeUsuario, JInternalFrame home) {
        
        initComponents();

        setSize(new Dimension(1280, 720)); //Seta o tamanho da tela ao abrir
        setLocationRelativeTo(null); //"Desprende" a tela de qualquer outro elemento
        
        //Ativa o menu lateral de navegação
        ativarMenu();
        
        this.permissaoUsuario=permissaoUsuario; //Armazena a permissão de usuário vinda da tela de login para habilitar ou não os recursos
        
        LocalTime horario = LocalTime.now(); //Recebe o período do dia
        verificarPeriodo(horario);
        
        //Faz com que a tela home preencha todo o JDesktop
        home.setBounds(0, 0, jDesktopPane1.getWidth(), jDesktopPane1.getHeight()); 
        this.home = home;
        jDesktopPane1.add(home);
        home.setVisible(true);

        //Detalhe da mensagem ao usuário
        txtNomeUsuario.setText(nomeUsuario + "!");
    }

    //Verifica o período do dia para a saudação ao usuário
    public void verificarPeriodo(LocalTime horario) {
        int hora = horario.getHour();

        if (hora >= 6 && hora < 12) {
            txtPeriodoDia.setText("Bom dia,");
        } else if (hora >= 12 && hora < 18) {
            txtPeriodoDia.setText("Boa tarde,");
        } else {
            txtPeriodoDia.setText("Boa noite,");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Main = new javax.swing.JPanel();
        MenuLateral = new javax.swing.JPanel();
        btn_menuHome = new javax.swing.JPanel();
        indicador1 = new javax.swing.JPanel();
        label1 = new javax.swing.JLabel();
        btn_menuCadastros = new javax.swing.JPanel();
        indicador2 = new javax.swing.JPanel();
        label2 = new javax.swing.JLabel();
        btn_menuEstoque = new javax.swing.JPanel();
        indicador3 = new javax.swing.JPanel();
        label3 = new javax.swing.JLabel();
        btn_menuVendas = new javax.swing.JPanel();
        indicador4 = new javax.swing.JPanel();
        lebal4 = new javax.swing.JLabel();
        btn_menuCompras = new javax.swing.JPanel();
        indicador5 = new javax.swing.JPanel();
        label5 = new javax.swing.JLabel();
        btn_menuRelatorios = new javax.swing.JPanel();
        indicador6 = new javax.swing.JPanel();
        label6 = new javax.swing.JLabel();
        btn_menuLogOff = new javax.swing.JPanel();
        indicador7 = new javax.swing.JPanel();
        label7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNomeUsuario = new javax.swing.JLabel();
        txtPeriodoDia = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuSistema = new javax.swing.JMenu();
        menuEncerrarSecao = new javax.swing.JMenuItem();
        menuTrocarUsuario = new javax.swing.JMenuItem();
        menuCadastros = new javax.swing.JMenu();
        menuCadUsuario = new javax.swing.JMenuItem();
        menuCadCliente = new javax.swing.JMenuItem();
        menuCadFornecedor = new javax.swing.JMenuItem();
        menuCadProduto = new javax.swing.JMenuItem();
        menuCadCategoria = new javax.swing.JMenuItem();
        menuEstoque = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        menuRelatorios = new javax.swing.JMenu();
        menuVendas = new javax.swing.JMenu();
        menuNovaVenda = new javax.swing.JMenuItem();
        menuHistoricoVendas = new javax.swing.JMenuItem();
        menuCompras = new javax.swing.JMenu();
        menuNovaCompra = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Novo Lar Materiais de Construção");
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(14, 33, 69));
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setResizable(false);
        setSize(new java.awt.Dimension(1280, 720));

        Main.setBackground(new java.awt.Color(255, 255, 255));

        MenuLateral.setBackground(new java.awt.Color(14, 33, 69));
        MenuLateral.setPreferredSize(new java.awt.Dimension(245, 572));
        MenuLateral.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_menuHome.setBackground(new java.awt.Color(41, 57, 100));
        btn_menuHome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_menuHome.setPreferredSize(new java.awt.Dimension(250, 40));
        btn_menuHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_menuHomeMousePressed(evt);
            }
        });

        indicador1.setBackground(new java.awt.Color(255, 255, 255));
        indicador1.setPreferredSize(new java.awt.Dimension(5, 50));

        javax.swing.GroupLayout indicador1Layout = new javax.swing.GroupLayout(indicador1);
        indicador1.setLayout(indicador1Layout);
        indicador1Layout.setHorizontalGroup(
            indicador1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        indicador1Layout.setVerticalGroup(
            indicador1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        label1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        label1.setText("Home");

        javax.swing.GroupLayout btn_menuHomeLayout = new javax.swing.GroupLayout(btn_menuHome);
        btn_menuHome.setLayout(btn_menuHomeLayout);
        btn_menuHomeLayout.setHorizontalGroup(
            btn_menuHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_menuHomeLayout.createSequentialGroup()
                .addComponent(indicador1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(label1)
                .addGap(0, 96, Short.MAX_VALUE))
        );
        btn_menuHomeLayout.setVerticalGroup(
            btn_menuHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(indicador1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(btn_menuHomeLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(label1)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        MenuLateral.add(btn_menuHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 200, 50));

        btn_menuCadastros.setBackground(new java.awt.Color(41, 57, 100));
        btn_menuCadastros.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_menuCadastros.setPreferredSize(new java.awt.Dimension(250, 40));
        btn_menuCadastros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_menuCadastrosMousePressed(evt);
            }
        });

        indicador2.setBackground(new java.awt.Color(255, 255, 255));
        indicador2.setOpaque(false);
        indicador2.setPreferredSize(new java.awt.Dimension(5, 50));

        javax.swing.GroupLayout indicador2Layout = new javax.swing.GroupLayout(indicador2);
        indicador2.setLayout(indicador2Layout);
        indicador2Layout.setHorizontalGroup(
            indicador2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        indicador2Layout.setVerticalGroup(
            indicador2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        label2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        label2.setText("Cadastros");

        javax.swing.GroupLayout btn_menuCadastrosLayout = new javax.swing.GroupLayout(btn_menuCadastros);
        btn_menuCadastros.setLayout(btn_menuCadastrosLayout);
        btn_menuCadastrosLayout.setHorizontalGroup(
            btn_menuCadastrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_menuCadastrosLayout.createSequentialGroup()
                .addComponent(indicador2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(label2)
                .addGap(0, 72, Short.MAX_VALUE))
        );
        btn_menuCadastrosLayout.setVerticalGroup(
            btn_menuCadastrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(indicador2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(btn_menuCadastrosLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(label2)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        MenuLateral.add(btn_menuCadastros, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 200, 50));

        btn_menuEstoque.setBackground(new java.awt.Color(41, 57, 100));
        btn_menuEstoque.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_menuEstoque.setOpaque(false);
        btn_menuEstoque.setPreferredSize(new java.awt.Dimension(250, 40));
        btn_menuEstoque.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_menuEstoqueMousePressed(evt);
            }
        });

        indicador3.setBackground(new java.awt.Color(255, 255, 255));
        indicador3.setOpaque(false);
        indicador3.setPreferredSize(new java.awt.Dimension(5, 50));

        javax.swing.GroupLayout indicador3Layout = new javax.swing.GroupLayout(indicador3);
        indicador3.setLayout(indicador3Layout);
        indicador3Layout.setHorizontalGroup(
            indicador3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        indicador3Layout.setVerticalGroup(
            indicador3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        label3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        label3.setText("Estoque");

        javax.swing.GroupLayout btn_menuEstoqueLayout = new javax.swing.GroupLayout(btn_menuEstoque);
        btn_menuEstoque.setLayout(btn_menuEstoqueLayout);
        btn_menuEstoqueLayout.setHorizontalGroup(
            btn_menuEstoqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_menuEstoqueLayout.createSequentialGroup()
                .addComponent(indicador3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 83, Short.MAX_VALUE))
        );
        btn_menuEstoqueLayout.setVerticalGroup(
            btn_menuEstoqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(indicador3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(btn_menuEstoqueLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(label3)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        MenuLateral.add(btn_menuEstoque, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 200, 50));

        btn_menuVendas.setBackground(new java.awt.Color(41, 57, 100));
        btn_menuVendas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_menuVendas.setOpaque(false);
        btn_menuVendas.setPreferredSize(new java.awt.Dimension(250, 40));
        btn_menuVendas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_menuVendasMousePressed(evt);
            }
        });

        indicador4.setBackground(new java.awt.Color(255, 255, 255));
        indicador4.setOpaque(false);
        indicador4.setPreferredSize(new java.awt.Dimension(5, 50));

        javax.swing.GroupLayout indicador4Layout = new javax.swing.GroupLayout(indicador4);
        indicador4.setLayout(indicador4Layout);
        indicador4Layout.setHorizontalGroup(
            indicador4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        indicador4Layout.setVerticalGroup(
            indicador4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        lebal4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lebal4.setText("Nova Venda");

        javax.swing.GroupLayout btn_menuVendasLayout = new javax.swing.GroupLayout(btn_menuVendas);
        btn_menuVendas.setLayout(btn_menuVendasLayout);
        btn_menuVendasLayout.setHorizontalGroup(
            btn_menuVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_menuVendasLayout.createSequentialGroup()
                .addComponent(indicador4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(lebal4)
                .addGap(0, 57, Short.MAX_VALUE))
        );
        btn_menuVendasLayout.setVerticalGroup(
            btn_menuVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(indicador4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(btn_menuVendasLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lebal4)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        MenuLateral.add(btn_menuVendas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 200, 50));

        btn_menuCompras.setBackground(new java.awt.Color(41, 57, 100));
        btn_menuCompras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_menuCompras.setOpaque(false);
        btn_menuCompras.setPreferredSize(new java.awt.Dimension(250, 40));
        btn_menuCompras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_menuComprasMousePressed(evt);
            }
        });

        indicador5.setBackground(new java.awt.Color(255, 255, 255));
        indicador5.setOpaque(false);
        indicador5.setPreferredSize(new java.awt.Dimension(5, 50));

        javax.swing.GroupLayout indicador5Layout = new javax.swing.GroupLayout(indicador5);
        indicador5.setLayout(indicador5Layout);
        indicador5Layout.setHorizontalGroup(
            indicador5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        indicador5Layout.setVerticalGroup(
            indicador5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        label5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        label5.setText("Nova Compra");

        javax.swing.GroupLayout btn_menuComprasLayout = new javax.swing.GroupLayout(btn_menuCompras);
        btn_menuCompras.setLayout(btn_menuComprasLayout);
        btn_menuComprasLayout.setHorizontalGroup(
            btn_menuComprasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_menuComprasLayout.createSequentialGroup()
                .addComponent(indicador5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(label5)
                .addGap(0, 46, Short.MAX_VALUE))
        );
        btn_menuComprasLayout.setVerticalGroup(
            btn_menuComprasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(indicador5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(btn_menuComprasLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(label5)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        MenuLateral.add(btn_menuCompras, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 200, 50));

        btn_menuRelatorios.setBackground(new java.awt.Color(41, 57, 100));
        btn_menuRelatorios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_menuRelatorios.setPreferredSize(new java.awt.Dimension(250, 40));
        btn_menuRelatorios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_menuRelatoriosMousePressed(evt);
            }
        });

        indicador6.setBackground(new java.awt.Color(255, 255, 255));
        indicador6.setOpaque(false);
        indicador6.setPreferredSize(new java.awt.Dimension(5, 50));

        javax.swing.GroupLayout indicador6Layout = new javax.swing.GroupLayout(indicador6);
        indicador6.setLayout(indicador6Layout);
        indicador6Layout.setHorizontalGroup(
            indicador6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        indicador6Layout.setVerticalGroup(
            indicador6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        label6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        label6.setText("Relatórios");

        javax.swing.GroupLayout btn_menuRelatoriosLayout = new javax.swing.GroupLayout(btn_menuRelatorios);
        btn_menuRelatorios.setLayout(btn_menuRelatoriosLayout);
        btn_menuRelatoriosLayout.setHorizontalGroup(
            btn_menuRelatoriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_menuRelatoriosLayout.createSequentialGroup()
                .addComponent(indicador6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 64, Short.MAX_VALUE))
        );
        btn_menuRelatoriosLayout.setVerticalGroup(
            btn_menuRelatoriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(indicador6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(btn_menuRelatoriosLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(label6)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        MenuLateral.add(btn_menuRelatorios, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, 200, 50));

        btn_menuLogOff.setBackground(new java.awt.Color(41, 57, 100));
        btn_menuLogOff.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_menuLogOff.setOpaque(false);
        btn_menuLogOff.setPreferredSize(new java.awt.Dimension(250, 40));
        btn_menuLogOff.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_menuLogOffMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_menuLogOffMouseReleased(evt);
            }
        });
        btn_menuLogOff.setLayout(null);

        indicador7.setBackground(new java.awt.Color(255, 255, 255));
        indicador7.setOpaque(false);
        indicador7.setPreferredSize(new java.awt.Dimension(5, 50));

        javax.swing.GroupLayout indicador7Layout = new javax.swing.GroupLayout(indicador7);
        indicador7.setLayout(indicador7Layout);
        indicador7Layout.setHorizontalGroup(
            indicador7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        indicador7Layout.setVerticalGroup(
            indicador7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        btn_menuLogOff.add(indicador7);
        indicador7.setBounds(0, 0, 5, 50);

        label7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        label7.setForeground(new java.awt.Color(255, 255, 255));
        label7.setText("Encerrar Seção");
        btn_menuLogOff.add(label7);
        label7.setBounds(60, 10, 100, 20);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/menuIcon-LogOff.png"))); // NOI18N
        btn_menuLogOff.add(jLabel2);
        jLabel2.setBounds(20, 0, 37, 32);

        MenuLateral.add(btn_menuLogOff, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 630, 200, 50));

        txtNomeUsuario.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtNomeUsuario.setForeground(new java.awt.Color(255, 255, 255));
        txtNomeUsuario.setText("nome");
        MenuLateral.add(txtNomeUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, -1, -1));

        txtPeriodoDia.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtPeriodoDia.setForeground(new java.awt.Color(255, 255, 255));
        txtPeriodoDia.setText("Período,");
        MenuLateral.add(txtPeriodoDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, -1, -1));

        jDesktopPane1.setBackground(new java.awt.Color(255, 255, 255));
        jDesktopPane1.setPreferredSize(new java.awt.Dimension(1080, 720));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1036, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout MainLayout = new javax.swing.GroupLayout(Main);
        Main.setLayout(MainLayout);
        MainLayout.setHorizontalGroup(
            MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainLayout.createSequentialGroup()
                .addComponent(MenuLateral, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1036, Short.MAX_VALUE))
        );
        MainLayout.setVerticalGroup(
            MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MenuLateral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        getContentPane().add(Main, java.awt.BorderLayout.CENTER);

        menuSistema.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/systemIcon.png"))); // NOI18N
        menuSistema.setText("Sistema");
        menuSistema.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        menuEncerrarSecao.setText("Encerrar Seção");
        menuEncerrarSecao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                menuEncerrarSecaoMouseReleased(evt);
            }
        });
        menuEncerrarSecao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEncerrarSecaoActionPerformed(evt);
            }
        });
        menuSistema.add(menuEncerrarSecao);

        menuTrocarUsuario.setText("Trocar Usuário");
        menuTrocarUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                menuTrocarUsuarioMouseReleased(evt);
            }
        });
        menuTrocarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuTrocarUsuarioActionPerformed(evt);
            }
        });
        menuSistema.add(menuTrocarUsuario);

        jMenuBar1.add(menuSistema);

        menuCadastros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/cadastroIcon.png"))); // NOI18N
        menuCadastros.setText("Cadastros");
        menuCadastros.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        menuCadUsuario.setText("Funcionario");
        menuCadUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadUsuarioActionPerformed(evt);
            }
        });
        menuCadastros.add(menuCadUsuario);

        menuCadCliente.setText("Cliente");
        menuCadCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                menuCadClienteMouseReleased(evt);
            }
        });
        menuCadastros.add(menuCadCliente);

        menuCadFornecedor.setText("Fornecedor");
        menuCadFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadFornecedorActionPerformed(evt);
            }
        });
        menuCadastros.add(menuCadFornecedor);

        menuCadProduto.setText("Produto");
        menuCadProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadProdutoActionPerformed(evt);
            }
        });
        menuCadastros.add(menuCadProduto);

        menuCadCategoria.setText("Categoria");
        menuCadCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadCategoriaActionPerformed(evt);
            }
        });
        menuCadastros.add(menuCadCategoria);

        jMenuBar1.add(menuCadastros);

        menuEstoque.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/estoqueIcon.png"))); // NOI18N
        menuEstoque.setText("Estoque");
        menuEstoque.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jMenuItem8.setText("Consultar Estoque");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        menuEstoque.add(jMenuItem8);

        jMenuBar1.add(menuEstoque);

        menuRelatorios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/relatorioIcon.png"))); // NOI18N
        menuRelatorios.setText("Relatórios");
        menuRelatorios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuRelatorios.setEnabled(false);
        jMenuBar1.add(menuRelatorios);

        menuVendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/vendasIcon.png"))); // NOI18N
        menuVendas.setText("Vendas");
        menuVendas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        menuNovaVenda.setText("Nova Venda");
        menuNovaVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuNovaVendaActionPerformed(evt);
            }
        });
        menuVendas.add(menuNovaVenda);

        menuHistoricoVendas.setText("Histórico de Vendas");
        menuHistoricoVendas.setEnabled(false);
        menuVendas.add(menuHistoricoVendas);

        jMenuBar1.add(menuVendas);

        menuCompras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/comprasIcon.png"))); // NOI18N
        menuCompras.setText("Compras");
        menuCompras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        menuNovaCompra.setText("Nova Compra");
        menuNovaCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuNovaCompraActionPerformed(evt);
            }
        });
        menuCompras.add(menuNovaCompra);

        jMenuBar1.add(menuCompras);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menuEncerrarSecaoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuEncerrarSecaoMouseReleased
        // TODO add your handling code here:
        
        //Pergunta ao usuário se quer encerrar a Seção
        String[] options = {"Encerrar Seção", "Cancelar"};

        confirmarEncerrarSecao = JOptionPane.showOptionDialog(
                this, "Tem certeza que deseja encerrar a seção?", "Confirmação", JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE, null, options, options[0]
        );

        //Se sim, encerra o sistema
        if (confirmarEncerrarSecao == JOptionPane.YES_OPTION) {
            // = false;
            System.exit(0);
        }
    }//GEN-LAST:event_menuEncerrarSecaoMouseReleased

    private void menuEncerrarSecaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEncerrarSecaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuEncerrarSecaoActionPerformed

    private void menuTrocarUsuarioMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuTrocarUsuarioMouseReleased
        // TODO add your handling code here:

        String[] options = {"Trocar", "Cancelar"}; // Textos personalizados dos botões

        confirmacaoTrocaUsuario = JOptionPane.showOptionDialog(
                this, "Tem certeza que deseja trocar de usuário?", "Confirmação", JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE, null, options, options[0]
        );

        //Fecha a tela atual e reabre a de login
        if (confirmacaoTrocaUsuario == JOptionPane.YES_OPTION) {
            dispose();
            new TelaLogin().setVisible(true);
        }
    }//GEN-LAST:event_menuTrocarUsuarioMouseReleased

    private void menuTrocarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuTrocarUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuTrocarUsuarioActionPerformed

    private void menuCadUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadUsuarioActionPerformed
        // TODO add your handling code here:

        //Verifica a permissão do usuário antes de abrir a tela
        if (permissaoUsuario == 1) {
            TelaCadFuncionario telaCadFunc = new TelaCadFuncionario();
            telaCadFunc.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Permissão de administrador necessária!");
        }
    }//GEN-LAST:event_menuCadUsuarioActionPerformed

    private void menuCadClienteMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuCadClienteMouseReleased
        // TODO add your handling code here:
        
        //Verifica a permissão do usuário antes de abrir a tela
        if (permissaoUsuario == 1) {
            TelaCadCliente telaCadCli = new TelaCadCliente();
            telaCadCli.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Permissão de administrador necessária!");
        }
    }//GEN-LAST:event_menuCadClienteMouseReleased

    private void menuCadFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadFornecedorActionPerformed
        // TODO add your handling code here:
        
        //Verifica a permissão do usuário antes de abrir a tela
        if (permissaoUsuario == 1) {
            TelaCadFornecedor telaCadForn = new TelaCadFornecedor();
            telaCadForn.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Permissão de administrador necessária!");
        }
    }//GEN-LAST:event_menuCadFornecedorActionPerformed

    private void menuCadProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadProdutoActionPerformed
        // TODO add your handling code here:

        TelaCadProduto telaCadProd = new TelaCadProduto();

        telaCadProd.setVisible(true);
    }//GEN-LAST:event_menuCadProdutoActionPerformed

    private void menuCadCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadCategoriaActionPerformed
        // TODO add your handling code here:
        TelaCadCategoria telaCadCat = new TelaCadCategoria();

        telaCadCat.setVisible(true);
    }//GEN-LAST:event_menuCadCategoriaActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
        TelaDeEstoque telaDeEstoque = new TelaDeEstoque();
        telaDeEstoque.setBounds(0, 0, jDesktopPane1.getWidth(), jDesktopPane1.getHeight()); //Faz com que a tela preencha todo o JDesktop e seja centralizada
        
        //Remove as outras telas do JDesktop e seta a desejada
        jDesktopPane1.removeAll();
        jDesktopPane1.add(telaDeEstoque);
        telaDeEstoque.setVisible(true);
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void menuNovaVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuNovaVendaActionPerformed
        // TODO add your handling code here:

        telaVenda = new TelaVenda(permissaoUsuario);
        
        //Remove as outras telas do JDesktop e seta a desejada
        jDesktopPane1.removeAll();
        jDesktopPane1.add(telaVenda);
        telaVenda.setVisible(true);
    }//GEN-LAST:event_menuNovaVendaActionPerformed

    private void menuNovaCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuNovaCompraActionPerformed
        // TODO add your handling code here:

        if (permissaoUsuario == 1) {
            TelaCompra telaCompra = new TelaCompra();
            telaCompra.setBounds(0, 0, jDesktopPane1.getWidth(), jDesktopPane1.getHeight()); //Faz com que a tela preencha todo o JDesktop e seja centralizada
            
            //Remove as outras telas do JDesktop e seta a desejada
            jDesktopPane1.removeAll();
            jDesktopPane1.add(telaCompra);
            telaCompra.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Permissão de administrador necessária!");
        }

    }//GEN-LAST:event_menuNovaCompraActionPerformed

    private void btn_menuHomeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_menuHomeMousePressed
        // TODO add your handling code here:
        
        //Efeito de "hover" do botão ; Seta a tela desejada 
        setColor(btn_menuHome, label1);
        indicador1.setOpaque(true);
        resetColor(new JPanel[]{btn_menuCadastros, btn_menuEstoque, btn_menuVendas, btn_menuCompras, btn_menuRelatorios},
                new JPanel[]{indicador2, indicador3, indicador4, indicador5, indicador6}, new JLabel[]{label2, label3, lebal4, label5, label6});

        jDesktopPane1.removeAll();
        jDesktopPane1.add(home);
        home.setVisible(true);
    }//GEN-LAST:event_btn_menuHomeMousePressed

    private void btn_menuCadastrosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_menuCadastrosMousePressed
        // TODO add your handling code here:
        
        JOptionPane.showMessageDialog(null, "Use a barra superior, por enquanto esse recurso está indisponível!");
        
        //Efeito de "hover" do botão ; Seta a tela desejada
//        setColor(btn_menuCadastros, label2);
//        indicador2.setOpaque(true);
//        resetColor(new JPanel[]{btn_menuHome, btn_menuEstoque, btn_menuVendas, btn_menuCompras, btn_menuRelatorios},
//                new JPanel[]{indicador1, indicador3, indicador4, indicador5, indicador6}, new JLabel[]{label1, label3, lebal4, label5, label6});
    }//GEN-LAST:event_btn_menuCadastrosMousePressed

    private void btn_menuEstoqueMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_menuEstoqueMousePressed
        // TODO add your handling code here:
        
        //Efeito de "hover" do botão ; Seta a tela desejada
        setColor(btn_menuEstoque, label3);
        indicador3.setOpaque(true);
        resetColor(new JPanel[]{btn_menuCadastros, btn_menuHome, btn_menuVendas, btn_menuCompras, btn_menuRelatorios},
                new JPanel[]{indicador2, indicador1, indicador4, indicador5, indicador6}, new JLabel[]{label1, label2, lebal4, label5, label6});
        
        TelaDeEstoque telaDeEstoque = new TelaDeEstoque();
        telaDeEstoque.setBounds(0, 0, jDesktopPane1.getWidth(), jDesktopPane1.getHeight()); //Faz com que a tela preencha todo o JDesktop e seja centralizada
        
        jDesktopPane1.removeAll();
        jDesktopPane1.add(telaDeEstoque);
        telaDeEstoque.setVisible(true);
        
        
    }//GEN-LAST:event_btn_menuEstoqueMousePressed

    private void btn_menuVendasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_menuVendasMousePressed
        // TODO add your handling code here:
        
        //Efeito de "hover" do botão ; Seta a tela desejada
        setColor(btn_menuVendas, lebal4);
        indicador4.setOpaque(true);
        resetColor(new JPanel[]{btn_menuCadastros, btn_menuEstoque, btn_menuHome, btn_menuCompras, btn_menuRelatorios},
                new JPanel[]{indicador2, indicador3, indicador1, indicador5, indicador6}, new JLabel[]{label1, label2, label3, label5, label6});
        
        telaVenda = new TelaVenda(permissaoUsuario);
        
        jDesktopPane1.removeAll();
        jDesktopPane1.add(telaVenda);
        telaVenda.setVisible(true);
    }//GEN-LAST:event_btn_menuVendasMousePressed

    private void btn_menuComprasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_menuComprasMousePressed
        // TODO add your handling code here:
        
        //Executa a função somente se o usuário tiver permissão 
        if (permissaoUsuario == 1) {
            
            //Efeito de "hover" do botão ; Seta a tela desejada
            setColor(btn_menuCompras, label5);
            indicador5.setOpaque(true);
            resetColor(new JPanel[]{btn_menuCadastros, btn_menuEstoque, btn_menuVendas, btn_menuHome, btn_menuRelatorios},
                    new JPanel[]{indicador2, indicador3, indicador4, indicador1, indicador6}, new JLabel[]{label1, label2, label3, lebal4, label6});

            TelaCompra telaCompra = new TelaCompra();
            telaCompra.setBounds(0, 0, jDesktopPane1.getWidth(), jDesktopPane1.getHeight()); //Faz com que a tela preencha todo o JDesktop e seja centralizada

            jDesktopPane1.removeAll();
            jDesktopPane1.add(telaCompra);
            telaCompra.setVisible(true);
        }
        else{
            JOptionPane.showMessageDialog(this, "Permissão de administrador necessária!");
        }
    }//GEN-LAST:event_btn_menuComprasMousePressed

    private void btn_menuRelatoriosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_menuRelatoriosMousePressed
        // TODO add your handling code here:
        
        //DESCOMENTAR QUANDO O SISTEMA DE RELATÓRIOS ESTIVER PRONTO
        
        JOptionPane.showMessageDialog(null, "Relatórios em breve!");
        
//        setColor(btn_menuRelatorios, label6);
//        indicador6.setOpaque(true);
//        resetColor(new JPanel[]{btn_menuCadastros, btn_menuEstoque, btn_menuVendas, btn_menuCompras, btn_menuHome},
//                new JPanel[]{indicador2, indicador3, indicador4, indicador5, indicador1}, new JLabel[]{label1, label2, label3, lebal4, label5});
    }//GEN-LAST:event_btn_menuRelatoriosMousePressed

    private void btn_menuLogOffMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_menuLogOffMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_menuLogOffMousePressed

    private void btn_menuLogOffMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_menuLogOffMouseReleased
        // TODO add your handling code here:

        String[] options = {"Encerrar Secao", "Cancelar"};

        confirmarEncerrarSecao = JOptionPane.showOptionDialog(
                this, "Tem certeza que deseja encerrar a secao?", "Confirmação", JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE, null, options, options[0]
        );

        if (confirmarEncerrarSecao == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_btn_menuLogOffMouseReleased

    //Função que muda a cor do botão que está selecionado
    private void setColor(JPanel botao, JLabel label) {
        botao.setBackground(new Color(41, 57, 100));
        label.setForeground(Color.white);
    }

    //Se outro botão está selecionado, a cor dos outros reseta
    private void resetColor(JPanel[] botao, JPanel[] indicadores, JLabel[] label) {
        for (int i = 0; i < botao.length; i++) {
            botao[i].setBackground(new Color(14, 33, 69));
            botao[i].setOpaque(true);
            label[i].setForeground(new Color(187, 187, 187));
        }
        for (JPanel indicadore : indicadores) {
            indicadore.setOpaque(false);
        }

    }

    //Ativa o menu de navegação lateral
    private void ativarMenu() {
        setColor(btn_menuHome, label1);
        indicador1.setOpaque(true);
        resetColor(new JPanel[]{btn_menuCadastros, btn_menuEstoque, btn_menuVendas, btn_menuCompras, btn_menuRelatorios},
                new JPanel[]{indicador2, indicador3, indicador4, indicador5, indicador6}, new JLabel[]{label2, label3, lebal4, label5, label6});
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Main;
    private javax.swing.JPanel MenuLateral;
    private javax.swing.JPanel btn_menuCadastros;
    private javax.swing.JPanel btn_menuCompras;
    private javax.swing.JPanel btn_menuEstoque;
    private javax.swing.JPanel btn_menuHome;
    private javax.swing.JPanel btn_menuLogOff;
    private javax.swing.JPanel btn_menuRelatorios;
    private javax.swing.JPanel btn_menuVendas;
    private javax.swing.JPanel indicador1;
    private javax.swing.JPanel indicador2;
    private javax.swing.JPanel indicador3;
    private javax.swing.JPanel indicador4;
    private javax.swing.JPanel indicador5;
    private javax.swing.JPanel indicador6;
    private javax.swing.JPanel indicador7;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel label2;
    private javax.swing.JLabel label3;
    private javax.swing.JLabel label5;
    private javax.swing.JLabel label6;
    private javax.swing.JLabel label7;
    private javax.swing.JLabel lebal4;
    private javax.swing.JMenuItem menuCadCategoria;
    private javax.swing.JMenuItem menuCadCliente;
    private javax.swing.JMenuItem menuCadFornecedor;
    private javax.swing.JMenuItem menuCadProduto;
    private javax.swing.JMenuItem menuCadUsuario;
    private javax.swing.JMenu menuCadastros;
    private javax.swing.JMenu menuCompras;
    private javax.swing.JMenuItem menuEncerrarSecao;
    private javax.swing.JMenu menuEstoque;
    private javax.swing.JMenuItem menuHistoricoVendas;
    private javax.swing.JMenuItem menuNovaCompra;
    private javax.swing.JMenuItem menuNovaVenda;
    private javax.swing.JMenu menuRelatorios;
    private javax.swing.JMenu menuSistema;
    private javax.swing.JMenuItem menuTrocarUsuario;
    private javax.swing.JMenu menuVendas;
    private javax.swing.JLabel txtNomeUsuario;
    private javax.swing.JLabel txtPeriodoDia;
    // End of variables declaration//GEN-END:variables
}
