/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ViewPrincipal;

import DAO.VendaDAO;
import ViewLogin.TelaLogin;
import ViewCadastro.TelaCadCategoria;
import ViewCadastro.TelaCadCliente;
import ViewCadastro.TelaCadFornecedor;
import ViewCadastro.TelaCadFuncionario;
import ViewCadastro.TelaCadProduto;
import ViewCompra.TelaCompra;
import ViewEstoque.TelaEstoque;
import ViewVenda.TelaVenda;
import java.awt.Color;
import java.awt.Dimension;
import java.time.LocalTime;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.Timer;

/**
 *
 * @author Kaio Dias
 */
public class TelaPrincipal extends javax.swing.JFrame {

    private int confirmacaoTrocaUsuario;
    private int confirmarEncerrarSecao;
    private boolean janelaAberta = true;

    private int permissaoUsuario;
    private String nomeUsuario;

    private TelaLogin telaLogin;

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal(int permissaoUsuario, String nomeUsuario) {
        initComponents();

        setSize(new Dimension(1280, 720));
        setLocationRelativeTo(null);
        ativarMenu();

        LocalTime horario = LocalTime.now();

        this.permissaoUsuario = permissaoUsuario;
        if (permissaoUsuario != 1) {
            btnMostrar.setEnabled(false);
            btnMostrar.setSelected(true);
        }

        txtNomeUsuario.setText(nomeUsuario + "!");
        verificarPeriodo(horario);

        Timer timer = new Timer(900, e -> {
            VendaDAO v = new VendaDAO();
            String totalVendas = "Valor total das vendas: R$" + String.valueOf(v.totalVendasMes());
            String numVendas = "Quantidades de vendas: " + String.valueOf(v.numVendasMes());
            if (!btnMostrar.isSelected()) {
                txtTotalVendasMes.setText(totalVendas);
                txtQuantidadeVendasMes.setText(numVendas);
            }
        });
        timer.start();
    }

    public void verificarPeriodo(LocalTime horario) {
        int hora = horario.getHour();

        if (hora >= 6 && hora < 12) {
            txtPeriodoDia.setText("Bom dia,");
        } else if (hora >= 12 && hora < 18) {
            txtPeriodoDia.setText("Boa tarde,");
        } else {
            txtPeriodoDia.setText("Boa noite,");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jDesktopPane2 = new javax.swing.JDesktopPane();
        jPanel4 = new javax.swing.JPanel();
        btn_menuHome = new javax.swing.JPanel();
        indicador1 = new javax.swing.JPanel();
        label1 = new javax.swing.JLabel();
        btn_menuCadastros = new javax.swing.JPanel();
        indicador2 = new javax.swing.JPanel();
        label2 = new javax.swing.JLabel();
        btn_menuEstoque = new javax.swing.JPanel();
        indicador3 = new javax.swing.JPanel();
        label3 = new javax.swing.JLabel();
        btn_menuVendas = new javax.swing.JPanel();
        indicador4 = new javax.swing.JPanel();
        lebal4 = new javax.swing.JLabel();
        btn_menuCompras = new javax.swing.JPanel();
        indicador5 = new javax.swing.JPanel();
        label5 = new javax.swing.JLabel();
        btn_menuRelatorios = new javax.swing.JPanel();
        indicador6 = new javax.swing.JPanel();
        label6 = new javax.swing.JLabel();
        btn_menuLogOff = new javax.swing.JPanel();
        indicador7 = new javax.swing.JPanel();
        label7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNomeUsuario = new javax.swing.JLabel();
        txtPeriodoDia = new javax.swing.JLabel();
        painelVendasMes = new Outros.PanelRound();
        panelRound2 = new Outros.PanelRound();
        jLabel1 = new javax.swing.JLabel();
        txtTotalVendasMes = new javax.swing.JLabel();
        txtQuantidadeVendasMes = new javax.swing.JLabel();
        btnMostrar = new javax.swing.JCheckBox();
        painelProdBaixoEstoque = new Outros.PanelRound();
        panelRound5 = new Outros.PanelRound();
        jLabel3 = new javax.swing.JLabel();
        painelAniversariantes = new Outros.PanelRound();
        panelRound7 = new Outros.PanelRound();
        jLabel4 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuSistema = new javax.swing.JMenu();
        menuEncerrarSecao = new javax.swing.JMenuItem();
        menuTrocarUsuario = new javax.swing.JMenuItem();
        menuCadastros = new javax.swing.JMenu();
        menuCadUsuario = new javax.swing.JMenuItem();
        menuCadCliente = new javax.swing.JMenuItem();
        menuCadFornecedor = new javax.swing.JMenuItem();
        menuCadProduto = new javax.swing.JMenuItem();
        menuCadCategoria = new javax.swing.JMenuItem();
        menuEstoque = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        menuRelatorios = new javax.swing.JMenu();
        menuVendas = new javax.swing.JMenu();
        menuNovaVenda = new javax.swing.JMenuItem();
        menuCompras = new javax.swing.JMenu();
        menuNovaCompra = new javax.swing.JMenuItem();

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Novo Lar Materiais de Construção");
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(14, 33, 69));
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setUndecorated(true);
        setSize(new java.awt.Dimension(1280, 720));

        jDesktopPane2.setBackground(new java.awt.Color(255, 255, 255));
        jDesktopPane2.setPreferredSize(new java.awt.Dimension(962, 768));

        jPanel4.setBackground(new java.awt.Color(14, 33, 69));
        jPanel4.setPreferredSize(new java.awt.Dimension(245, 572));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_menuHome.setBackground(new java.awt.Color(41, 57, 100));
        btn_menuHome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_menuHome.setPreferredSize(new java.awt.Dimension(250, 40));
        btn_menuHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_menuHomeMousePressed(evt);
            }
        });

        indicador1.setBackground(new java.awt.Color(255, 255, 255));
        indicador1.setPreferredSize(new java.awt.Dimension(5, 50));

        javax.swing.GroupLayout indicador1Layout = new javax.swing.GroupLayout(indicador1);
        indicador1.setLayout(indicador1Layout);
        indicador1Layout.setHorizontalGroup(
            indicador1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        indicador1Layout.setVerticalGroup(
            indicador1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        label1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        label1.setText("Home");

        javax.swing.GroupLayout btn_menuHomeLayout = new javax.swing.GroupLayout(btn_menuHome);
        btn_menuHome.setLayout(btn_menuHomeLayout);
        btn_menuHomeLayout.setHorizontalGroup(
            btn_menuHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_menuHomeLayout.createSequentialGroup()
                .addComponent(indicador1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(label1)
                .addGap(0, 96, Short.MAX_VALUE))
        );
        btn_menuHomeLayout.setVerticalGroup(
            btn_menuHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(indicador1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(btn_menuHomeLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(label1)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel4.add(btn_menuHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 200, 50));

        btn_menuCadastros.setBackground(new java.awt.Color(41, 57, 100));
        btn_menuCadastros.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_menuCadastros.setOpaque(false);
        btn_menuCadastros.setPreferredSize(new java.awt.Dimension(250, 40));
        btn_menuCadastros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_menuCadastrosMousePressed(evt);
            }
        });

        indicador2.setBackground(new java.awt.Color(255, 255, 255));
        indicador2.setOpaque(false);
        indicador2.setPreferredSize(new java.awt.Dimension(5, 50));

        javax.swing.GroupLayout indicador2Layout = new javax.swing.GroupLayout(indicador2);
        indicador2.setLayout(indicador2Layout);
        indicador2Layout.setHorizontalGroup(
            indicador2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        indicador2Layout.setVerticalGroup(
            indicador2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        label2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        label2.setText("Cadastros");

        javax.swing.GroupLayout btn_menuCadastrosLayout = new javax.swing.GroupLayout(btn_menuCadastros);
        btn_menuCadastros.setLayout(btn_menuCadastrosLayout);
        btn_menuCadastrosLayout.setHorizontalGroup(
            btn_menuCadastrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_menuCadastrosLayout.createSequentialGroup()
                .addComponent(indicador2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(label2)
                .addGap(0, 72, Short.MAX_VALUE))
        );
        btn_menuCadastrosLayout.setVerticalGroup(
            btn_menuCadastrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(indicador2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(btn_menuCadastrosLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(label2)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel4.add(btn_menuCadastros, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 200, 50));

        btn_menuEstoque.setBackground(new java.awt.Color(41, 57, 100));
        btn_menuEstoque.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_menuEstoque.setOpaque(false);
        btn_menuEstoque.setPreferredSize(new java.awt.Dimension(250, 40));
        btn_menuEstoque.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_menuEstoqueMousePressed(evt);
            }
        });

        indicador3.setBackground(new java.awt.Color(255, 255, 255));
        indicador3.setOpaque(false);
        indicador3.setPreferredSize(new java.awt.Dimension(5, 50));

        javax.swing.GroupLayout indicador3Layout = new javax.swing.GroupLayout(indicador3);
        indicador3.setLayout(indicador3Layout);
        indicador3Layout.setHorizontalGroup(
            indicador3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        indicador3Layout.setVerticalGroup(
            indicador3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        label3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        label3.setText("Estoque");

        javax.swing.GroupLayout btn_menuEstoqueLayout = new javax.swing.GroupLayout(btn_menuEstoque);
        btn_menuEstoque.setLayout(btn_menuEstoqueLayout);
        btn_menuEstoqueLayout.setHorizontalGroup(
            btn_menuEstoqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_menuEstoqueLayout.createSequentialGroup()
                .addComponent(indicador3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 83, Short.MAX_VALUE))
        );
        btn_menuEstoqueLayout.setVerticalGroup(
            btn_menuEstoqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(indicador3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(btn_menuEstoqueLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(label3)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel4.add(btn_menuEstoque, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 200, 50));

        btn_menuVendas.setBackground(new java.awt.Color(41, 57, 100));
        btn_menuVendas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_menuVendas.setOpaque(false);
        btn_menuVendas.setPreferredSize(new java.awt.Dimension(250, 40));
        btn_menuVendas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_menuVendasMousePressed(evt);
            }
        });

        indicador4.setBackground(new java.awt.Color(255, 255, 255));
        indicador4.setOpaque(false);
        indicador4.setPreferredSize(new java.awt.Dimension(5, 50));

        javax.swing.GroupLayout indicador4Layout = new javax.swing.GroupLayout(indicador4);
        indicador4.setLayout(indicador4Layout);
        indicador4Layout.setHorizontalGroup(
            indicador4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        indicador4Layout.setVerticalGroup(
            indicador4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        lebal4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lebal4.setText("Vendas");

        javax.swing.GroupLayout btn_menuVendasLayout = new javax.swing.GroupLayout(btn_menuVendas);
        btn_menuVendas.setLayout(btn_menuVendasLayout);
        btn_menuVendasLayout.setHorizontalGroup(
            btn_menuVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_menuVendasLayout.createSequentialGroup()
                .addComponent(indicador4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(lebal4, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 83, Short.MAX_VALUE))
        );
        btn_menuVendasLayout.setVerticalGroup(
            btn_menuVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(indicador4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(btn_menuVendasLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lebal4)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel4.add(btn_menuVendas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 200, 50));

        btn_menuCompras.setBackground(new java.awt.Color(41, 57, 100));
        btn_menuCompras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_menuCompras.setOpaque(false);
        btn_menuCompras.setPreferredSize(new java.awt.Dimension(250, 40));
        btn_menuCompras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_menuComprasMousePressed(evt);
            }
        });

        indicador5.setBackground(new java.awt.Color(255, 255, 255));
        indicador5.setOpaque(false);
        indicador5.setPreferredSize(new java.awt.Dimension(5, 50));

        javax.swing.GroupLayout indicador5Layout = new javax.swing.GroupLayout(indicador5);
        indicador5.setLayout(indicador5Layout);
        indicador5Layout.setHorizontalGroup(
            indicador5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        indicador5Layout.setVerticalGroup(
            indicador5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        label5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        label5.setText("Compras");

        javax.swing.GroupLayout btn_menuComprasLayout = new javax.swing.GroupLayout(btn_menuCompras);
        btn_menuCompras.setLayout(btn_menuComprasLayout);
        btn_menuComprasLayout.setHorizontalGroup(
            btn_menuComprasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_menuComprasLayout.createSequentialGroup()
                .addComponent(indicador5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 61, Short.MAX_VALUE))
        );
        btn_menuComprasLayout.setVerticalGroup(
            btn_menuComprasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(indicador5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(btn_menuComprasLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(label5)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel4.add(btn_menuCompras, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 200, 50));

        btn_menuRelatorios.setBackground(new java.awt.Color(41, 57, 100));
        btn_menuRelatorios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_menuRelatorios.setOpaque(false);
        btn_menuRelatorios.setPreferredSize(new java.awt.Dimension(250, 40));
        btn_menuRelatorios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_menuRelatoriosMousePressed(evt);
            }
        });

        indicador6.setBackground(new java.awt.Color(255, 255, 255));
        indicador6.setOpaque(false);
        indicador6.setPreferredSize(new java.awt.Dimension(5, 50));

        javax.swing.GroupLayout indicador6Layout = new javax.swing.GroupLayout(indicador6);
        indicador6.setLayout(indicador6Layout);
        indicador6Layout.setHorizontalGroup(
            indicador6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        indicador6Layout.setVerticalGroup(
            indicador6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        label6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        label6.setText("Relatórios");

        javax.swing.GroupLayout btn_menuRelatoriosLayout = new javax.swing.GroupLayout(btn_menuRelatorios);
        btn_menuRelatorios.setLayout(btn_menuRelatoriosLayout);
        btn_menuRelatoriosLayout.setHorizontalGroup(
            btn_menuRelatoriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_menuRelatoriosLayout.createSequentialGroup()
                .addComponent(indicador6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 64, Short.MAX_VALUE))
        );
        btn_menuRelatoriosLayout.setVerticalGroup(
            btn_menuRelatoriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(indicador6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(btn_menuRelatoriosLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(label6)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel4.add(btn_menuRelatorios, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, 200, 50));

        btn_menuLogOff.setBackground(new java.awt.Color(41, 57, 100));
        btn_menuLogOff.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_menuLogOff.setOpaque(false);
        btn_menuLogOff.setPreferredSize(new java.awt.Dimension(250, 40));
        btn_menuLogOff.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_menuLogOffMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_menuLogOffMouseReleased(evt);
            }
        });
        btn_menuLogOff.setLayout(null);

        indicador7.setBackground(new java.awt.Color(255, 255, 255));
        indicador7.setOpaque(false);
        indicador7.setPreferredSize(new java.awt.Dimension(5, 50));

        javax.swing.GroupLayout indicador7Layout = new javax.swing.GroupLayout(indicador7);
        indicador7.setLayout(indicador7Layout);
        indicador7Layout.setHorizontalGroup(
            indicador7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        indicador7Layout.setVerticalGroup(
            indicador7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        btn_menuLogOff.add(indicador7);
        indicador7.setBounds(0, 0, 5, 50);

        label7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        label7.setForeground(new java.awt.Color(255, 255, 255));
        label7.setText("Encerrar Seção");
        btn_menuLogOff.add(label7);
        label7.setBounds(60, 10, 100, 20);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/menuIcon-LogOff.png"))); // NOI18N
        btn_menuLogOff.add(jLabel2);
        jLabel2.setBounds(20, 0, 37, 32);

        jPanel4.add(btn_menuLogOff, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 630, 200, 50));

        txtNomeUsuario.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtNomeUsuario.setForeground(new java.awt.Color(255, 255, 255));
        txtNomeUsuario.setText("nome");
        jPanel4.add(txtNomeUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, -1, -1));

        txtPeriodoDia.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtPeriodoDia.setForeground(new java.awt.Color(255, 255, 255));
        txtPeriodoDia.setText("Período,");
        jPanel4.add(txtPeriodoDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        painelVendasMes.setBackground(new java.awt.Color(14, 33, 69));
        painelVendasMes.setForeground(new java.awt.Color(255, 255, 255));
        painelVendasMes.setRoundBottomLeft(30);
        painelVendasMes.setRoundBottomRight(30);
        painelVendasMes.setRoundTopLeft(30);
        painelVendasMes.setRoundTopRight(30);

        panelRound2.setBackground(new java.awt.Color(31, 53, 126));
        panelRound2.setRoundTopLeft(30);
        panelRound2.setRoundTopRight(30);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Vendas do mês");

        javax.swing.GroupLayout panelRound2Layout = new javax.swing.GroupLayout(panelRound2);
        panelRound2.setLayout(panelRound2Layout);
        panelRound2Layout.setHorizontalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addContainerGap(209, Short.MAX_VALUE))
        );
        panelRound2Layout.setVerticalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        txtTotalVendasMes.setBackground(new java.awt.Color(14, 33, 69));
        txtTotalVendasMes.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        txtTotalVendasMes.setForeground(new java.awt.Color(255, 255, 255));
        txtTotalVendasMes.setOpaque(true);

        txtQuantidadeVendasMes.setBackground(new java.awt.Color(14, 33, 69));
        txtQuantidadeVendasMes.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        txtQuantidadeVendasMes.setForeground(new java.awt.Color(255, 255, 255));
        txtQuantidadeVendasMes.setOpaque(true);

        btnMostrar.setForeground(new java.awt.Color(255, 255, 255));
        btnMostrar.setText("Exibir / Ocultar");
        btnMostrar.setBorder(null);
        btnMostrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMostrarMouseClicked(evt);
            }
        });
        btnMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelVendasMesLayout = new javax.swing.GroupLayout(painelVendasMes);
        painelVendasMes.setLayout(painelVendasMesLayout);
        painelVendasMesLayout.setHorizontalGroup(
            painelVendasMesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelRound2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelVendasMesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(painelVendasMesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnMostrar)
                    .addGroup(painelVendasMesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtTotalVendasMes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtQuantidadeVendasMes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        painelVendasMesLayout.setVerticalGroup(
            painelVendasMesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelVendasMesLayout.createSequentialGroup()
                .addComponent(panelRound2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(txtTotalVendasMes, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtQuantidadeVendasMes, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnMostrar)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        painelProdBaixoEstoque.setBackground(new java.awt.Color(14, 33, 69));
        painelProdBaixoEstoque.setRoundBottomLeft(30);
        painelProdBaixoEstoque.setRoundBottomRight(30);
        painelProdBaixoEstoque.setRoundTopLeft(30);
        painelProdBaixoEstoque.setRoundTopRight(30);

        panelRound5.setBackground(new java.awt.Color(31, 53, 126));
        panelRound5.setRoundTopLeft(30);
        panelRound5.setRoundTopRight(30);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Produtos com baixo estoque");

        javax.swing.GroupLayout panelRound5Layout = new javax.swing.GroupLayout(panelRound5);
        panelRound5.setLayout(panelRound5Layout);
        panelRound5Layout.setHorizontalGroup(
            panelRound5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound5Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        panelRound5Layout.setVerticalGroup(
            panelRound5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap())
        );

        javax.swing.GroupLayout painelProdBaixoEstoqueLayout = new javax.swing.GroupLayout(painelProdBaixoEstoque);
        painelProdBaixoEstoque.setLayout(painelProdBaixoEstoqueLayout);
        painelProdBaixoEstoqueLayout.setHorizontalGroup(
            painelProdBaixoEstoqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelRound5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        painelProdBaixoEstoqueLayout.setVerticalGroup(
            painelProdBaixoEstoqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelProdBaixoEstoqueLayout.createSequentialGroup()
                .addComponent(panelRound5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        painelAniversariantes.setBackground(new java.awt.Color(14, 33, 69));
        painelAniversariantes.setRoundBottomLeft(30);
        painelAniversariantes.setRoundBottomRight(30);
        painelAniversariantes.setRoundTopLeft(30);
        painelAniversariantes.setRoundTopRight(30);

        panelRound7.setBackground(new java.awt.Color(31, 53, 126));
        panelRound7.setRoundTopLeft(30);
        panelRound7.setRoundTopRight(30);

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Aniversariantes do mês");

        javax.swing.GroupLayout panelRound7Layout = new javax.swing.GroupLayout(panelRound7);
        panelRound7.setLayout(panelRound7Layout);
        panelRound7Layout.setHorizontalGroup(
            panelRound7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound7Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelRound7Layout.setVerticalGroup(
            panelRound7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout painelAniversariantesLayout = new javax.swing.GroupLayout(painelAniversariantes);
        painelAniversariantes.setLayout(painelAniversariantesLayout);
        painelAniversariantesLayout.setHorizontalGroup(
            painelAniversariantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelRound7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        painelAniversariantesLayout.setVerticalGroup(
            painelAniversariantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelAniversariantesLayout.createSequentialGroup()
                .addComponent(panelRound7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(308, Short.MAX_VALUE))
        );

        jDesktopPane2.setLayer(jPanel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(painelVendasMes, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(painelProdBaixoEstoque, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(painelAniversariantes, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane2Layout = new javax.swing.GroupLayout(jDesktopPane2);
        jDesktopPane2.setLayout(jDesktopPane2Layout);
        jDesktopPane2Layout.setHorizontalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane2Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(135, 135, 135)
                .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane2Layout.createSequentialGroup()
                        .addComponent(painelVendasMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 115, Short.MAX_VALUE)
                        .addComponent(painelProdBaixoEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(painelAniversariantes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(135, 135, 135))
        );
        jDesktopPane2Layout.setVerticalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 768, Short.MAX_VALUE)
            .addGroup(jDesktopPane2Layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(painelProdBaixoEstoque, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(painelVendasMes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(72, 72, 72)
                .addComponent(painelAniversariantes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jDesktopPane2, java.awt.BorderLayout.CENTER);

        menuSistema.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/systemIcon.png"))); // NOI18N
        menuSistema.setText("Sistema");
        menuSistema.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        menuEncerrarSecao.setText("Encerrar Seção");
        menuEncerrarSecao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                menuEncerrarSecaoMouseReleased(evt);
            }
        });
        menuEncerrarSecao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEncerrarSecaoActionPerformed(evt);
            }
        });
        menuSistema.add(menuEncerrarSecao);

        menuTrocarUsuario.setText("Trocar Usuário");
        menuTrocarUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                menuTrocarUsuarioMouseReleased(evt);
            }
        });
        menuTrocarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuTrocarUsuarioActionPerformed(evt);
            }
        });
        menuSistema.add(menuTrocarUsuario);

        jMenuBar1.add(menuSistema);

        menuCadastros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/cadastroIcon.png"))); // NOI18N
        menuCadastros.setText("Cadastros");
        menuCadastros.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        menuCadUsuario.setText("Funcionario");
        menuCadUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadUsuarioActionPerformed(evt);
            }
        });
        menuCadastros.add(menuCadUsuario);

        menuCadCliente.setText("Cliente");
        menuCadCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                menuCadClienteMouseReleased(evt);
            }
        });
        menuCadastros.add(menuCadCliente);

        menuCadFornecedor.setText("Fornecedor");
        menuCadFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadFornecedorActionPerformed(evt);
            }
        });
        menuCadastros.add(menuCadFornecedor);

        menuCadProduto.setText("Produto");
        menuCadProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadProdutoActionPerformed(evt);
            }
        });
        menuCadastros.add(menuCadProduto);

        menuCadCategoria.setText("Categoria");
        menuCadCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadCategoriaActionPerformed(evt);
            }
        });
        menuCadastros.add(menuCadCategoria);

        jMenuBar1.add(menuCadastros);

        menuEstoque.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/estoqueIcon.png"))); // NOI18N
        menuEstoque.setText("Estoque");
        menuEstoque.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jMenuItem8.setText("Consultar Estoque");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        menuEstoque.add(jMenuItem8);

        jMenuBar1.add(menuEstoque);

        menuRelatorios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/relatorioIcon.png"))); // NOI18N
        menuRelatorios.setText("Relatórios");
        menuRelatorios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuBar1.add(menuRelatorios);

        menuVendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/vendasIcon.png"))); // NOI18N
        menuVendas.setText("Vendas");
        menuVendas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        menuNovaVenda.setText("Nova Venda");
        menuNovaVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuNovaVendaActionPerformed(evt);
            }
        });
        menuVendas.add(menuNovaVenda);

        jMenuBar1.add(menuVendas);

        menuCompras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/comprasIcon.png"))); // NOI18N
        menuCompras.setText("Compras");
        menuCompras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        menuNovaCompra.setText("Nova Compra");
        menuNovaCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuNovaCompraActionPerformed(evt);
            }
        });
        menuCompras.add(menuNovaCompra);

        jMenuBar1.add(menuCompras);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menuEncerrarSecaoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuEncerrarSecaoMouseReleased
        // TODO add your handling code here:
        String[] options = {"Encerrar Secao", "Cancelar"};

        confirmarEncerrarSecao = JOptionPane.showOptionDialog(
                this, "Tem certeza que deseja encerrar a secao?", "Confirmação", JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE, null, options, options[0]
        );

        if (confirmarEncerrarSecao == JOptionPane.YES_OPTION) {
            janelaAberta = false;
            System.exit(0);
        }
    }//GEN-LAST:event_menuEncerrarSecaoMouseReleased

    private void menuEncerrarSecaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEncerrarSecaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuEncerrarSecaoActionPerformed

    private void menuTrocarUsuarioMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuTrocarUsuarioMouseReleased
        // TODO add your handling code here:

        String[] options = {"Trocar", "Cancelar"}; // Textos personalizados dos botões

        confirmacaoTrocaUsuario = JOptionPane.showOptionDialog(
                this, "Tem certeza que deseja trocar de usuário?", "Confirmação", JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE, null, options, options[0]
        );

        if (confirmacaoTrocaUsuario == JOptionPane.YES_OPTION) {
            janelaAberta = false;
            dispose();
            new TelaLogin().setVisible(true);
        }
    }//GEN-LAST:event_menuTrocarUsuarioMouseReleased

    private void menuTrocarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuTrocarUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuTrocarUsuarioActionPerformed

    private void menuCadUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadUsuarioActionPerformed
        // TODO add your handling code here:

        if (permissaoUsuario == 1) {

            TelaCadFuncionario telaCadFunc = new TelaCadFuncionario();
            telaCadFunc.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Permissão de administrador necessária!");
        }
    }//GEN-LAST:event_menuCadUsuarioActionPerformed

    private void menuCadClienteMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuCadClienteMouseReleased
        // TODO add your handling code here:
        if (permissaoUsuario == 1) {

            TelaCadCliente telaCadCli = new TelaCadCliente();
            telaCadCli.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Permissão de administrador necessária!");
        }
    }//GEN-LAST:event_menuCadClienteMouseReleased

    private void menuCadFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadFornecedorActionPerformed
        // TODO add your handling code here:
        if (permissaoUsuario == 1) {
            TelaCadFornecedor telaCadForn = new TelaCadFornecedor();
            telaCadForn.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Permissão de administrador necessária!");
        }
    }//GEN-LAST:event_menuCadFornecedorActionPerformed

    private void menuCadProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadProdutoActionPerformed
        // TODO add your handling code here:

        TelaCadProduto telaCadProd = new TelaCadProduto();

        telaCadProd.setVisible(true);
    }//GEN-LAST:event_menuCadProdutoActionPerformed

    private void menuCadCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadCategoriaActionPerformed
        // TODO add your handling code here:
        TelaCadCategoria telaCadCat = new TelaCadCategoria();

        telaCadCat.setVisible(true);
    }//GEN-LAST:event_menuCadCategoriaActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:

        TelaEstoque telaEstoque = new TelaEstoque();
        telaEstoque.setVisible(true);
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void menuNovaVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuNovaVendaActionPerformed
        // TODO add your handling code here:
        TelaVenda telaVenda = new TelaVenda();
        telaVenda.setVisible(true);
    }//GEN-LAST:event_menuNovaVendaActionPerformed

    private void menuNovaCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuNovaCompraActionPerformed
        // TODO add your handling code here:

        if (permissaoUsuario == 1) {
            TelaCompra telaCompra = new TelaCompra();
            telaCompra.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Permissão de administrador necessária!");
        }

    }//GEN-LAST:event_menuNovaCompraActionPerformed


    private void btn_menuHomeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_menuHomeMousePressed
        // TODO add your handling code here:
        setColor(btn_menuHome, label1);
        indicador1.setOpaque(true);
        resetColor(new JPanel[]{btn_menuCadastros, btn_menuEstoque, btn_menuVendas, btn_menuCompras, btn_menuRelatorios},
                new JPanel[]{indicador2, indicador3, indicador4, indicador5, indicador6}, new JLabel[]{label2, label3, lebal4, label5, label6});


    }//GEN-LAST:event_btn_menuHomeMousePressed

    private void btn_menuCadastrosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_menuCadastrosMousePressed
        // TODO add your handling code here:
        setColor(btn_menuCadastros, label2);
        indicador2.setOpaque(true);
        resetColor(new JPanel[]{btn_menuHome, btn_menuEstoque, btn_menuVendas, btn_menuCompras, btn_menuRelatorios},
                new JPanel[]{indicador1, indicador3, indicador4, indicador5, indicador6}, new JLabel[]{label1, label3, lebal4, label5, label6});
    }//GEN-LAST:event_btn_menuCadastrosMousePressed

    private void btn_menuEstoqueMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_menuEstoqueMousePressed
        // TODO add your handling code here:
        setColor(btn_menuEstoque, label3);
        indicador3.setOpaque(true);
        resetColor(new JPanel[]{btn_menuCadastros, btn_menuHome, btn_menuVendas, btn_menuCompras, btn_menuRelatorios},
                new JPanel[]{indicador2, indicador1, indicador4, indicador5, indicador6}, new JLabel[]{label1, label2, lebal4, label5, label6});
    }//GEN-LAST:event_btn_menuEstoqueMousePressed

    private void btn_menuVendasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_menuVendasMousePressed
        // TODO add your handling code here:
        setColor(btn_menuVendas, lebal4);
        indicador4.setOpaque(true);
        resetColor(new JPanel[]{btn_menuCadastros, btn_menuEstoque, btn_menuHome, btn_menuCompras, btn_menuRelatorios},
                new JPanel[]{indicador2, indicador3, indicador1, indicador5, indicador6}, new JLabel[]{label1, label2, label3, label5, label6});
    }//GEN-LAST:event_btn_menuVendasMousePressed

    private void btn_menuComprasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_menuComprasMousePressed
        // TODO add your handling code here:
        setColor(btn_menuCompras, label5);
        indicador5.setOpaque(true);
        resetColor(new JPanel[]{btn_menuCadastros, btn_menuEstoque, btn_menuVendas, btn_menuHome, btn_menuRelatorios},
                new JPanel[]{indicador2, indicador3, indicador4, indicador1, indicador6}, new JLabel[]{label1, label2, label3, lebal4, label6});
    }//GEN-LAST:event_btn_menuComprasMousePressed

    private void btn_menuRelatoriosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_menuRelatoriosMousePressed
        // TODO add your handling code here:
        setColor(btn_menuRelatorios, label6);
        indicador6.setOpaque(true);
        resetColor(new JPanel[]{btn_menuCadastros, btn_menuEstoque, btn_menuVendas, btn_menuCompras, btn_menuHome},
                new JPanel[]{indicador2, indicador3, indicador4, indicador5, indicador1}, new JLabel[]{label1, label2, label3, lebal4, label5});
    }//GEN-LAST:event_btn_menuRelatoriosMousePressed

    private void btn_menuLogOffMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_menuLogOffMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_menuLogOffMousePressed

    private void btn_menuLogOffMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_menuLogOffMouseReleased
        // TODO add your handling code here:

        String[] options = {"Encerrar Secao", "Cancelar"};

        confirmarEncerrarSecao = JOptionPane.showOptionDialog(
                this, "Tem certeza que deseja encerrar a secao?", "Confirmação", JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE, null, options, options[0]
        );

        if (confirmarEncerrarSecao == JOptionPane.YES_OPTION) {
            janelaAberta = false;
            System.exit(0);
        }
    }//GEN-LAST:event_btn_menuLogOffMouseReleased

    private void btnMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMostrarActionPerformed

    private void btnMostrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMostrarMouseClicked
        // TODO add your handling code here:
        if (btnMostrar.isSelected()) {
            txtTotalVendasMes.setText("#########");
            txtQuantidadeVendasMes.setText("#########");
        }
    }//GEN-LAST:event_btnMostrarMouseClicked

    private void setColor(JPanel botao, JLabel label) {
        botao.setBackground(new Color(41, 57, 100));
        label.setForeground(Color.white);
    }

    private void resetColor(JPanel[] botao, JPanel[] indicadores, JLabel[] label) {
        for (int i = 0; i < botao.length; i++) {
            botao[i].setBackground(new Color(14, 33, 69));
            botao[i].setOpaque(true);
            label[i].setForeground(new Color(187, 187, 187));
        }
        for (int i = 0; i < indicadores.length; i++) {
            indicadores[i].setOpaque(false);
        }

    }

    private void ativarMenu() {
        setColor(btn_menuHome, label1);
        indicador1.setOpaque(true);
        resetColor(new JPanel[]{btn_menuCadastros, btn_menuEstoque, btn_menuVendas, btn_menuCompras, btn_menuRelatorios},
                new JPanel[]{indicador2, indicador3, indicador4, indicador5, indicador6}, new JLabel[]{label2, label3, lebal4, label5, label6});
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox btnMostrar;
    private javax.swing.JPanel btn_menuCadastros;
    private javax.swing.JPanel btn_menuCompras;
    private javax.swing.JPanel btn_menuEstoque;
    private javax.swing.JPanel btn_menuHome;
    private javax.swing.JPanel btn_menuLogOff;
    private javax.swing.JPanel btn_menuRelatorios;
    private javax.swing.JPanel btn_menuVendas;
    private javax.swing.JPanel indicador1;
    private javax.swing.JPanel indicador2;
    private javax.swing.JPanel indicador3;
    private javax.swing.JPanel indicador4;
    private javax.swing.JPanel indicador5;
    private javax.swing.JPanel indicador6;
    private javax.swing.JPanel indicador7;
    private javax.swing.JDesktopPane jDesktopPane2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel label2;
    private javax.swing.JLabel label3;
    private javax.swing.JLabel label5;
    private javax.swing.JLabel label6;
    private javax.swing.JLabel label7;
    private javax.swing.JLabel lebal4;
    private javax.swing.JMenuItem menuCadCategoria;
    private javax.swing.JMenuItem menuCadCliente;
    private javax.swing.JMenuItem menuCadFornecedor;
    private javax.swing.JMenuItem menuCadProduto;
    private javax.swing.JMenuItem menuCadUsuario;
    private javax.swing.JMenu menuCadastros;
    private javax.swing.JMenu menuCompras;
    private javax.swing.JMenuItem menuEncerrarSecao;
    private javax.swing.JMenu menuEstoque;
    private javax.swing.JMenuItem menuNovaCompra;
    private javax.swing.JMenuItem menuNovaVenda;
    private javax.swing.JMenu menuRelatorios;
    private javax.swing.JMenu menuSistema;
    private javax.swing.JMenuItem menuTrocarUsuario;
    private javax.swing.JMenu menuVendas;
    private Outros.PanelRound painelAniversariantes;
    private Outros.PanelRound painelProdBaixoEstoque;
    private Outros.PanelRound painelVendasMes;
    private Outros.PanelRound panelRound2;
    private Outros.PanelRound panelRound5;
    private Outros.PanelRound panelRound7;
    private javax.swing.JLabel txtNomeUsuario;
    private javax.swing.JLabel txtPeriodoDia;
    private javax.swing.JLabel txtQuantidadeVendasMes;
    private javax.swing.JLabel txtTotalVendasMes;
    // End of variables declaration//GEN-END:variables
}
